# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-12-16 12:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('Doctor', 'Doctor'), ('Nurse', 'Nurse')], max_length=10)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Department')),
            ],
        ),
        migrations.CreateModel(
            name='ExaminationResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('result', models.CharField(choices=[('Healthy', 'Healthy'), ('Corona', 'Corona'), ('Botism', 'Botism'), ('Dead', 'Dead')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalWorker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departments', models.ManyToManyField(related_name='workers', through='hospital.DepartmentWork', to='hospital.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Person'),
        ),
        migrations.AddField(
            model_name='hospitalworker',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Person'),
        ),
        migrations.AddField(
            model_name='examinationresult',
            name='examiner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examination_results', to='hospital.HospitalWorker'),
        ),
        migrations.AddField(
            model_name='examinationresult',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examination_results', to='hospital.Patient'),
        ),
        migrations.AddField(
            model_name='departmentwork',
            name='hospital_worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.HospitalWorker'),
        ),
        migrations.AddField(
            model_name='department',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='hospital.Hospital'),
        ),
    ]
