# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-12-15 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalWorker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('position', models.CharField(choices=[('Doctor', 'Doctor'), ('Nurse', 'Nurse')], max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='worker',
            name='departments',
        ),
        migrations.AlterField(
            model_name='department',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='hospital.Hospital'),
        ),
        migrations.AlterField(
            model_name='examinationresult',
            name='examiner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='hospital.HospitalWorker'),
        ),
        migrations.AlterField(
            model_name='examinationresult',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='hospital.Patient'),
        ),
        migrations.AlterField(
            model_name='examinationresult',
            name='result',
            field=models.CharField(choices=[('Healthy', 'Healthy'), ('Corona', 'Corona'), ('Botism', 'Botism'), ('Dead', 'Dead')], max_length=1),
        ),
        migrations.AlterField(
            model_name='examinationresult',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='examinationresult',
            index=models.Index(fields=['result'], name='hospital_ex_result_9c8d68_idx'),
        ),
        migrations.AddIndex(
            model_name='hospital',
            index=models.Index(fields=['name'], name='hospital_ho_name_d8f339_idx'),
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
        migrations.AddField(
            model_name='hospitalworker',
            name='departments',
            field=models.ManyToManyField(related_name='workers', to='hospital.Department'),
        ),
        migrations.AddIndex(
            model_name='hospitalworker',
            index=models.Index(fields=['position'], name='hospital_ho_positio_7e5294_idx'),
        ),
    ]
