# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-17 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(default='', max_length=200)),
                ('hospital_city', models.CharField(default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalExamination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examination_date', models.DateTimeField(verbose_name='exam date')),
                ('examination_result', models.CharField(choices=[('Healty', 'Healty'), ('CORONA', 'CORONA'), ('BOTISM', 'BOTISM'), ('DEAD', 'DEAD')], default='Healty', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people_name', models.CharField(default='', max_length=200)),
                ('age', models.CharField(default=0, max_length=200)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('Other', 'Other')], default='Male', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('people_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apphospital.People')),
            ],
            bases=('apphospital.people',),
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('people_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apphospital.People')),
                ('role', models.CharField(choices=[('Doc', 'Doctor'), ('Nur', 'Nurse')], default='Doctor', max_length=50)),
            ],
            bases=('apphospital.people',),
        ),
        migrations.AddField(
            model_name='department',
            name='hospital',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='apphospital.Hospital'),
        ),
        migrations.AddField(
            model_name='worker',
            name='department',
            field=models.ManyToManyField(to='apphospital.Department'),
        ),
        migrations.AddField(
            model_name='patient',
            name='department_in',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apphospital.Department'),
        ),
        migrations.AddField(
            model_name='medicalexamination',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apphospital.Patient'),
        ),
        migrations.AddField(
            model_name='medicalexamination',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apphospital.Worker'),
        ),
    ]
