# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-18 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphospital', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='department_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='hospital_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='hospital_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='medicalexamination',
            old_name='examination_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='people',
            old_name='people_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='medicalexamination',
            name='examination_result',
        ),
        migrations.AddField(
            model_name='medicalexamination',
            name='result',
            field=models.CharField(choices=[('Healty', 'Healty'), ('Corona', 'Corona'), ('Botism', 'Botism'), ('Dead', 'Dead')], default='Healty', max_length=20),
        ),
    ]
