# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-16 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apphospital', '0002_hospital_hospital_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=200)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apphospital.Hospital')),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('people_id', models.AutoField(primary_key=True, serialize=False)),
                ('people_name', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('Other', 'Other')], default='Male', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('people_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apphospital.People')),
                ('department_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apphospital.Department')),
            ],
            bases=('apphospital.people',),
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('people_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apphospital.People')),
                ('role', models.CharField(choices=[('Doc', 'Doctor'), ('Nur', 'Nurse')], default='Doctor', max_length=50)),
                ('department', models.ManyToManyField(to='apphospital.Department')),
            ],
            bases=('apphospital.people',),
        ),
    ]
