# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-02-05 16:36
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', models.CharField(choices=[(b'H', b'Healthy'), (b'C', b'Corona')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('city', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[(b'H', b'Habra'), (b'M', b'Male'), (b'O', b'Other'), (b'F', b'Female')], max_length=20)),
                ('age', models.IntegerField(validators=[django.core.validators.MaxValueValidator(120), django.core.validators.MinValueValidator(18)])),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid_examinations.Department')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[(b'H', b'Habra'), (b'M', b'Male'), (b'O', b'Other'), (b'F', b'Female')], max_length=20)),
                ('age', models.IntegerField(validators=[django.core.validators.MaxValueValidator(120), django.core.validators.MinValueValidator(18)])),
                ('job', models.CharField(choices=[(b'D', b'Doctor'), (b'N', b'Nurse')], max_length=20)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid_examinations.Department')),
            ],
        ),
        migrations.AddField(
            model_name='examination',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid_examinations.Patient'),
        ),
        migrations.AddField(
            model_name='examination',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid_examinations.Worker'),
        ),
        migrations.AddField(
            model_name='department',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid_examinations.Hospital'),
        ),
    ]
