# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-02-06 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_examinations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
